version: '3.7'
services:
  mysqldb:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  postgres:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Qwerty2wer45
      - POSTGRES_DB=app
      - POSTGRES_USER=admin
